### PR TITLE
my details

### PR DESCRIPTION
**Pull request by sarth23**

### CODE REVIEW

**Comment by ashiishme** [comment]
Your both PR is invalid because it doesn't follows the contribution guideline. The file name should be `sarth23.md` & you must add little more information.

Please don't create another PR but commit the changes on this same PR.

**Review by sarth23 — COMMENTED** [review]
Thanks I have done as you said

**Comment by ashiishme** [comment]
@sarth23  Your username is: `sarth23` the filename must be `sarth23.md`.

**Comment by ashiishme** [comment]
I am labeling this PR for `Hacktoberfest` but please fix the file name before it can be merged.

**Comment by sarth23** [comment]
> @sarth23 Your username is: `sarth23` the filename must be `sarth23.md`.
> 
> image

heh I changed it .Thanks

**Review by ashiishme — APPROVED** [review]
Looks good. You can always update your markdown file in future.

**Pull request merged**
