### PR TITLE
Added my full name with my github url

### PR DESCRIPTION
**Pull request by pr0d33p**

### CODE REVIEW

**Comment by ashiishme** [comment]
@pr0d33p  Please update the file with additional details as mentioned in contribution section. It has examples which you can reference.

**Review by ashiishme — CHANGES_REQUESTED** [review]
Based on the above comment, once you update this PR it will be merged.

**Comment by pr0d33p** [comment]
Updated

**Review by ashiishme — CHANGES_REQUESTED** [review]
File name doesn't match with the username.

**Comment by pr0d33p** [comment]
Oh okay, updated that too.

**Review by ashiishme — APPROVED** [review]

**Pull request merged**
