### PR TITLE
add_me

### PR DESCRIPTION
**Pull request by aryarfani**

### CODE REVIEW

**Comment by ashiishme** [comment]
@aryarfani Hi, thanks for the PR but can you please add more details as mentioned in this [example](https://github.com/ashiishme/open-source-enthusiasts#profile-details-example).

**Review by ashiishme — CHANGES_REQUESTED** [review]
Based on the above comment, once you update this PR it will be merged.

**Comment by aryarfani** [comment]
great will do mate

**Review by ashiishme — APPROVED** [review]
Great.

**Pull request merged**
