### PR TITLE
Create trevorcarter.md

### PR DESCRIPTION
**Pull request by trevorcarter83**
Added my profile

### CODE REVIEW

**Review by ashiishme — CHANGES_REQUESTED** [review]
Please add more details about yourself according to the new contribution guide.

**Comment by ashiishme** [comment]
The file name doesn't match with the username.

**Review by trevorcarter83 — COMMENTED** [review]
Changed according to new requirements.

**Comment by trevorcarter83** [comment]
Made requested changes.

**Review by ashiishme — APPROVED** [review]

**Pull request merged**
